### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by Nerdyvedi** [xiaohaoxiang/inpaint#1]
Hi, I am trying to run the main.cpp file. I am getting the following error
`In file included from /usr/include/c++/5/bits/stl_tempbuf.h:60:0,
                 from /usr/include/c++/5/bits/stl_algo.h:62,
                 from /usr/include/c++/5/algorithm:62,
                 from main.cpp:1:
/usr/include/c++/5/bits/stl_construct.h: In instantiation of 'void std::_Construct(_T1*, _Args&& ...) [with _T1 = P2i; _Args = {}]':  
/usr/include/c++/5/bits/stl_uninitialized.h:519:18:   required from 'static _ForwardIterator   std::__uninitialized_default_n_1<_TrivialValueType>::__uninit_default_n(_ForwardIterator, _Size) [with _ForwardIterator = P2i*;   _Size = long unsigned int; bool _TrivialValueType = false]'. 
/usr/include/c++/5/bits/stl_uninitialized.h:575:20:   required from '_ForwardIterator.  std::__uninitialized_default_n(_ForwardIterator, _Size) [with _ForwardIterator = P2i*; _Size = long unsigned int]'. 
/usr/include/c++/5/bits/stl_uninitialized.h:637:44:   required from '_ForwardIterator.  std::__uninitialized_default_n_a(_ForwardIterator, _Size, std::allocator<_Tp>&) [with _ForwardIterator = P2i*; _Size = long.  unsigned int; _Tp = P2i]'. 
/usr/include/c++/5/bits/vector.tcc:549:35:   required from 'void std::vector<_Tp, _Alloc>::_M_default_append(std::vector<_Tp,   _Alloc>::size_type) [with _Tp = P2i; _Alloc = std::allocator<P2i>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]'. 
/usr/include/c++/5/bits/stl_vector.h:676:21:   required from 'void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type) [with _Tp = P2i; _Alloc = std::allocator<P2i>; std::vector<_Tp, _Alloc>::size_type = long unsigned int]'
kdtree.hpp:200:11:   required from 'Kdtree<T>::Kdtree(It, It) [with It = std::__detail::_Node_iterator<P2i, true, true>; T = int]'
RBF.hpp:47:41:   required from 'void RBF(const cv::Mat&, cv::Mat&, const std::vector<P2i>&, Func, double) [with Func = Gaussian]'
main.cpp:133:4:   required from here
/usr/include/c++/5/bits/stl_construct.h:75:7: error: no matching function for call to 'P2i::P2i()'
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^
In file included from bilinear.h:6:0,  
                 from main.cpp:9:  
defs.hpp:10:21: note: candidate: P2i::P2i(int, int). 
  using cv::Point2i::Point_;  
                     ^
defs.hpp:10:21: note:   candidate expects 2 arguments, 0 provided.  
defs.hpp:10:21: note: candidate: P2i::P2i(const cv::Size_<int>&). 
defs.hpp:10:21: note:   candidate expects 1 argument, 0 provided. 
defs.hpp:10:21: note: candidate: P2i::P2i(const cv::Vec<int, 2>&). 
defs.hpp:10:21: note:   candidate expects 1 argument, 0 provided. 
defs.hpp:11:2: note: candidate: P2i::P2i(const Point2i&). 
  P2i(const cv::Point2i& p) :cv::Point2i(p) {}. 
  ^. 
defs.hpp:11:2: note:   candidate expects 1 argument, 0 provided. 
defs.hpp:8:8: note: candidate: P2i::P2i(const P2i&). 
 struct P2i :public cv::Point2i. 
        ^. 
defs.hpp:8:8: note:   candidate expects 1 argument, 0 provided. 
defs.hpp:8:8: note: candidate: P2i::P2i(P2i&&). 
defs.hpp:8:8: note:   candidate expects 1 argument, 0 provided. 
`

Using the following command:
g++ main.cpp -o main -std=c++17 -lstdc++fs

I also replaced #include<filesystem> with #include <experimental/filesystem>

**Comment by xiaohaoxiang** [comment]
I've update the Makefile, you would please try again?

You only compile one file `main.cpp`, which of course won't work.
